---
version: '3'
services:
  elemrv:
    build: .
    image: elements:v1
    container_name: elemenrv_container
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /home:/home
      - $XAUTHORITY:$XAUTHORITY:ro
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
    command: ["sleep", "infinity"]
